// Code generated by tools/gen_ids.py from the PyFLP event enums; DO NOT EDIT.

package pyflp

// IDGroup identifies the PyFLP EventEnum subclass an event ID belongs to.
type IDGroup int

const (
	GroupNone IDGroup = iota
	GroupPlugin
	GroupChannel
	GroupDisplayGroup
	GroupRack
	GroupTimeMarker
	GroupPatterns
	GroupPattern
	GroupArrangements
	GroupArrangement
	GroupTrack
	GroupInsert
	GroupMixer
	GroupSlot
	GroupProject
	GroupController
)

var groupNames = map[IDGroup]string{
	GroupNone: "",
	GroupPlugin: "PluginID",
	GroupChannel: "ChannelID",
	GroupDisplayGroup: "DisplayGroupID",
	GroupRack: "RackID",
	GroupTimeMarker: "TimeMarkerID",
	GroupPatterns: "PatternsID",
	GroupPattern: "PatternID",
	GroupArrangements: "ArrangementsID",
	GroupArrangement: "ArrangementID",
	GroupTrack: "TrackID",
	GroupInsert: "InsertID",
	GroupMixer: "MixerID",
	GroupSlot: "SlotID",
	GroupProject: "ProjectID",
	GroupController: "ControllerID",
}

// Event IDs. Names mirror PyFLP: ChannelID.New -> IDChannelNew. A leading
// underscore in PyFLP (deprecated / unsure) is dropped and flagged in the table.
const (
	IDPluginColor EventID = 128
	IDPluginIcon EventID = 155
	IDPluginInternalName EventID = 201
	IDPluginName EventID = 203
	IDPluginWrapper EventID = 212
	IDPluginData EventID = 213
	IDChannelIsEnabled EventID = 0
	IDChannelVolByte EventID = 2
	IDChannelPanByte EventID = 3
	IDChannelZipped EventID = 15
	IDChannelPingPongLoop EventID = 20
	IDChannelType EventID = 21
	IDChannelRoutedTo EventID = 22
	IDChannelIsLocked EventID = 32
	IDChannelNew EventID = 64
	IDChannelFreqTilt EventID = 69
	IDChannelFXFlags EventID = 70
	IDChannelCutoff EventID = 71
	IDChannelVolWord EventID = 72
	IDChannelPanWord EventID = 73
	IDChannelPreamp EventID = 74
	IDChannelFadeOut EventID = 75
	IDChannelFadeIn EventID = 76
	IDChannelResonance EventID = 83
	IDChannelStereoDelay EventID = 85
	IDChannelPogo EventID = 86
	IDChannelTimeShift EventID = 89
	IDChannelChildren EventID = 94
	IDChannelSwing EventID = 97
	IDChannelRingMod EventID = 131
	IDChannelCutGroup EventID = 132
	IDChannelRootNote EventID = 135
	IDChannelDelayModXY EventID = 138
	IDChannelReverb EventID = 139
	IDChannelStretchTime EventID = 140
	IDChannelFineTune EventID = 142
	IDChannelSamplerFlags EventID = 143
	IDChannelLayerFlags EventID = 144
	IDChannelGroupNum EventID = 145
	IDChannelAUSampleRate EventID = 153
	IDChannelName EventID = 192
	IDChannelSamplePath EventID = 196
	IDChannelDelay EventID = 209
	IDChannelParameters EventID = 215
	IDChannelEnvelopeLFO EventID = 218
	IDChannelLevels EventID = 219
	IDChannelPolyphony EventID = 221
	IDChannelTracking EventID = 228
	IDChannelLevelAdjusts EventID = 229
	IDChannelAutomation EventID = 234
	IDDisplayGroupName EventID = 231
	IDRackSwing EventID = 11
	IDRackFitToSteps EventID = 13
	IDRackWindowHeight EventID = 133
	IDTimeMarkerNumerator EventID = 33
	IDTimeMarkerDenominator EventID = 34
	IDTimeMarkerPosition EventID = 148
	IDTimeMarkerName EventID = 205
	IDPatternsPlayTruncatedNotes EventID = 30
	IDPatternsCurrentlySelected EventID = 67
	IDPatternLooped EventID = 26
	IDPatternNew EventID = 65
	IDPatternColor EventID = 150
	IDPatternName EventID = 193
	IDPatternChannelIID EventID = 160
	IDPattern161 EventID = 161
	IDPattern162 EventID = 162
	IDPatternLength EventID = 164
	IDPatternControllers EventID = 223
	IDPatternNotes EventID = 224
	IDArrangementsTimeSigNum EventID = 17
	IDArrangementsTimeSigBeat EventID = 18
	IDArrangementsCurrent EventID = 100
	IDArrangementsLoopPos EventID = 152
	IDArrangementsPLSelection EventID = 217
	IDArrangementNew EventID = 99
	IDArrangementName EventID = 241
	IDArrangementPlaylist EventID = 233
	IDTrackName EventID = 239
	IDTrackData EventID = 238
	IDInsertIcon EventID = 95
	IDInsertOutput EventID = 147
	IDInsertColor EventID = 149
	IDInsertInput EventID = 154
	IDInsertName EventID = 204
	IDInsertRouting EventID = 235
	IDInsertFlags EventID = 236
	IDMixerAPDC EventID = 29
	IDMixerParams EventID = 225
	IDSlotIndex EventID = 98
	IDProjectLoopActive EventID = 9
	IDProjectShowInfo EventID = 10
	IDProjectVolume EventID = 12
	IDProjectPanLaw EventID = 23
	IDProjectLicensed EventID = 28
	IDProjectTempoCoarse EventID = 66
	IDProjectPitch EventID = 80
	IDProjectTempoFine EventID = 93
	IDProjectCurGroupId EventID = 146
	IDProjectTempo EventID = 156
	IDProjectFLBuild EventID = 159
	IDProjectTitle EventID = 194
	IDProjectComments EventID = 195
	IDProjectUrl EventID = 197
	IDProjectRTFComments EventID = 198
	IDProjectFLVersion EventID = 199
	IDProjectLicensee EventID = 200
	IDProjectDataPath EventID = 202
	IDProjectGenre EventID = 206
	IDProjectArtists EventID = 207
	IDProjectTimestamp EventID = 237
	IDControllerMIDI EventID = 226
	IDControllerRemote EventID = 227
)

type idEntry struct {
	ID         EventID
	Group      IDGroup
	Name       string
	Deprecated bool
	Type       *EventType
}

var idTable = []idEntry{
	{IDPluginColor, GroupPlugin, "Color", false, ColorEvent},
	{IDPluginIcon, GroupPlugin, "Icon", false, U32Event},
	{IDPluginInternalName, GroupPlugin, "InternalName", false, nil},
	{IDPluginName, GroupPlugin, "Name", false, nil},
	{IDPluginWrapper, GroupPlugin, "Wrapper", false, WrapperEvent},
	{IDPluginData, GroupPlugin, "Data", false, nil},
	{IDChannelIsEnabled, GroupChannel, "IsEnabled", false, BoolEvent},
	{IDChannelVolByte, GroupChannel, "VolByte", true, U8Event},
	{IDChannelPanByte, GroupChannel, "PanByte", true, U8Event},
	{IDChannelZipped, GroupChannel, "Zipped", false, BoolEvent},
	{IDChannelPingPongLoop, GroupChannel, "PingPongLoop", false, BoolEvent},
	{IDChannelType, GroupChannel, "Type", false, U8Event},
	{IDChannelRoutedTo, GroupChannel, "RoutedTo", false, I8Event},
	{IDChannelIsLocked, GroupChannel, "IsLocked", false, BoolEvent},
	{IDChannelNew, GroupChannel, "New", false, U16Event},
	{IDChannelFreqTilt, GroupChannel, "FreqTilt", false, U16Event},
	{IDChannelFXFlags, GroupChannel, "FXFlags", false, U16Event},
	{IDChannelCutoff, GroupChannel, "Cutoff", false, U16Event},
	{IDChannelVolWord, GroupChannel, "VolWord", true, U16Event},
	{IDChannelPanWord, GroupChannel, "PanWord", true, U16Event},
	{IDChannelPreamp, GroupChannel, "Preamp", false, U16Event},
	{IDChannelFadeOut, GroupChannel, "FadeOut", false, U16Event},
	{IDChannelFadeIn, GroupChannel, "FadeIn", false, U16Event},
	{IDChannelResonance, GroupChannel, "Resonance", false, U16Event},
	{IDChannelStereoDelay, GroupChannel, "StereoDelay", false, U16Event},
	{IDChannelPogo, GroupChannel, "Pogo", false, U16Event},
	{IDChannelTimeShift, GroupChannel, "TimeShift", false, U16Event},
	{IDChannelChildren, GroupChannel, "Children", false, U16Event},
	{IDChannelSwing, GroupChannel, "Swing", false, U16Event},
	{IDChannelRingMod, GroupChannel, "RingMod", false, U16TupleEvent},
	{IDChannelCutGroup, GroupChannel, "CutGroup", false, U16TupleEvent},
	{IDChannelRootNote, GroupChannel, "RootNote", false, U32Event},
	{IDChannelDelayModXY, GroupChannel, "DelayModXY", false, U16TupleEvent},
	{IDChannelReverb, GroupChannel, "Reverb", false, U32Event},
	{IDChannelStretchTime, GroupChannel, "StretchTime", true, F32Event},
	{IDChannelFineTune, GroupChannel, "FineTune", false, I32Event},
	{IDChannelSamplerFlags, GroupChannel, "SamplerFlags", false, U32Event},
	{IDChannelLayerFlags, GroupChannel, "LayerFlags", false, U32Event},
	{IDChannelGroupNum, GroupChannel, "GroupNum", false, I32Event},
	{IDChannelAUSampleRate, GroupChannel, "AUSampleRate", false, U32Event},
	{IDChannelName, GroupChannel, "Name", true, nil},
	{IDChannelSamplePath, GroupChannel, "SamplePath", false, nil},
	{IDChannelDelay, GroupChannel, "Delay", false, DelayEvent},
	{IDChannelParameters, GroupChannel, "Parameters", false, ParametersEvent},
	{IDChannelEnvelopeLFO, GroupChannel, "EnvelopeLFO", false, EnvelopeLFOEvent},
	{IDChannelLevels, GroupChannel, "Levels", false, LevelsEvent},
	{IDChannelPolyphony, GroupChannel, "Polyphony", false, PolyphonyEvent},
	{IDChannelTracking, GroupChannel, "Tracking", false, TrackingEvent},
	{IDChannelLevelAdjusts, GroupChannel, "LevelAdjusts", false, LevelAdjustsEvent},
	{IDChannelAutomation, GroupChannel, "Automation", false, AutomationEvent},
	{IDDisplayGroupName, GroupDisplayGroup, "Name", false, nil},
	{IDRackSwing, GroupRack, "Swing", false, U8Event},
	{IDRackFitToSteps, GroupRack, "FitToSteps", true, U8Event},
	{IDRackWindowHeight, GroupRack, "WindowHeight", false, U32Event},
	{IDTimeMarkerNumerator, GroupTimeMarker, "Numerator", false, U8Event},
	{IDTimeMarkerDenominator, GroupTimeMarker, "Denominator", false, U8Event},
	{IDTimeMarkerPosition, GroupTimeMarker, "Position", false, U32Event},
	{IDTimeMarkerName, GroupTimeMarker, "Name", false, nil},
	{IDPatternsPlayTruncatedNotes, GroupPatterns, "PlayTruncatedNotes", false, BoolEvent},
	{IDPatternsCurrentlySelected, GroupPatterns, "CurrentlySelected", false, U16Event},
	{IDPatternLooped, GroupPattern, "Looped", false, BoolEvent},
	{IDPatternNew, GroupPattern, "New", false, U16Event},
	{IDPatternColor, GroupPattern, "Color", false, ColorEvent},
	{IDPatternName, GroupPattern, "Name", false, nil},
	{IDPatternChannelIID, GroupPattern, "ChannelIID", false, U32Event},
	{IDPattern161, GroupPattern, "161", true, I32Event},
	{IDPattern162, GroupPattern, "162", true, U32Event},
	{IDPatternLength, GroupPattern, "Length", false, U32Event},
	{IDPatternControllers, GroupPattern, "Controllers", false, ControllerEvent},
	{IDPatternNotes, GroupPattern, "Notes", false, NotesEvent},
	{IDArrangementsTimeSigNum, GroupArrangements, "TimeSigNum", false, U8Event},
	{IDArrangementsTimeSigBeat, GroupArrangements, "TimeSigBeat", false, U8Event},
	{IDArrangementsCurrent, GroupArrangements, "Current", false, U16Event},
	{IDArrangementsLoopPos, GroupArrangements, "LoopPos", true, U16TupleEvent},
	{IDArrangementsPLSelection, GroupArrangements, "PLSelection", false, PLSelectionEvent},
	{IDArrangementNew, GroupArrangement, "New", false, U16Event},
	{IDArrangementName, GroupArrangement, "Name", false, nil},
	{IDArrangementPlaylist, GroupArrangement, "Playlist", false, PlaylistEvent},
	{IDTrackName, GroupTrack, "Name", false, nil},
	{IDTrackData, GroupTrack, "Data", false, TrackEvent},
	{IDInsertIcon, GroupInsert, "Icon", false, I16Event},
	{IDInsertOutput, GroupInsert, "Output", false, I32Event},
	{IDInsertColor, GroupInsert, "Color", false, ColorEvent},
	{IDInsertInput, GroupInsert, "Input", false, I32Event},
	{IDInsertName, GroupInsert, "Name", false, nil},
	{IDInsertRouting, GroupInsert, "Routing", false, InsertRoutingEvent},
	{IDInsertFlags, GroupInsert, "Flags", false, InsertFlagsEvent},
	{IDMixerAPDC, GroupMixer, "APDC", false, nil},
	{IDMixerParams, GroupMixer, "Params", false, MixerParamsEvent},
	{IDSlotIndex, GroupSlot, "Index", false, U16Event},
	{IDProjectLoopActive, GroupProject, "LoopActive", false, BoolEvent},
	{IDProjectShowInfo, GroupProject, "ShowInfo", false, BoolEvent},
	{IDProjectVolume, GroupProject, "Volume", true, U8Event},
	{IDProjectPanLaw, GroupProject, "PanLaw", false, U8Event},
	{IDProjectLicensed, GroupProject, "Licensed", false, BoolEvent},
	{IDProjectTempoCoarse, GroupProject, "TempoCoarse", true, nil},
	{IDProjectPitch, GroupProject, "Pitch", false, I16Event},
	{IDProjectTempoFine, GroupProject, "TempoFine", true, nil},
	{IDProjectCurGroupId, GroupProject, "CurGroupId", false, I32Event},
	{IDProjectTempo, GroupProject, "Tempo", false, U32Event},
	{IDProjectFLBuild, GroupProject, "FLBuild", false, U32Event},
	{IDProjectTitle, GroupProject, "Title", false, nil},
	{IDProjectComments, GroupProject, "Comments", false, nil},
	{IDProjectUrl, GroupProject, "Url", false, nil},
	{IDProjectRTFComments, GroupProject, "RTFComments", true, nil},
	{IDProjectFLVersion, GroupProject, "FLVersion", false, AsciiEvent},
	{IDProjectLicensee, GroupProject, "Licensee", false, nil},
	{IDProjectDataPath, GroupProject, "DataPath", false, nil},
	{IDProjectGenre, GroupProject, "Genre", false, nil},
	{IDProjectArtists, GroupProject, "Artists", false, nil},
	{IDProjectTimestamp, GroupProject, "Timestamp", false, TimestampEvent},
	{IDControllerMIDI, GroupController, "MIDI", false, MIDIControllerEvent},
	{IDControllerRemote, GroupController, "Remote", false, RemoteControllerEvent},
}
